(window["webpackJsonp"] = window["webpackJsonp"] || []).push([["main"],{

/***/ "./src/$$_lazy_route_resource lazy recursive":
/*!**********************************************************!*\
  !*** ./src/$$_lazy_route_resource lazy namespace object ***!
  \**********************************************************/
/*! no static exports found */
/***/ (function(module, exports) {

function webpackEmptyAsyncContext(req) {
	// Here Promise.resolve().then() is used instead of new Promise() to prevent
	// uncaught exception popping up in devtools
	return Promise.resolve().then(function() {
		var e = new Error("Cannot find module '" + req + "'");
		e.code = 'MODULE_NOT_FOUND';
		throw e;
	});
}
webpackEmptyAsyncContext.keys = function() { return []; };
webpackEmptyAsyncContext.resolve = webpackEmptyAsyncContext;
module.exports = webpackEmptyAsyncContext;
webpackEmptyAsyncContext.id = "./src/$$_lazy_route_resource lazy recursive";

/***/ }),

/***/ "./src/app/app-routing.module.ts":
/*!***************************************!*\
  !*** ./src/app/app-routing.module.ts ***!
  \***************************************/
/*! exports provided: AppRoutingModule */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "AppRoutingModule", function() { return AppRoutingModule; });
/* harmony import */ var _angular_router__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! @angular/router */ "./node_modules/@angular/router/fesm5/router.js");
/* harmony import */ var _components_punch_punch_component__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! ./components/punch/punch.component */ "./src/app/components/punch/punch.component.ts");
/* harmony import */ var _app_component__WEBPACK_IMPORTED_MODULE_2__ = __webpack_require__(/*! ./app.component */ "./src/app/app.component.ts");



var routes = [
    {
        path: 'punch-list',
        component: _components_punch_punch_component__WEBPACK_IMPORTED_MODULE_1__["PunchComponent"]
    },
    {
        path: 'punch-list/:trade',
        component: _components_punch_punch_component__WEBPACK_IMPORTED_MODULE_1__["PunchComponent"]
    },
    {
        path: '',
        component: _app_component__WEBPACK_IMPORTED_MODULE_2__["AppComponent"]
    }
];
var AppRoutingModule = /** @class */ (function () {
    function AppRoutingModule() {
    }
    return AppRoutingModule;
}());



/***/ }),

/***/ "./src/app/app.component.css.shim.ngstyle.js":
/*!***************************************************!*\
  !*** ./src/app/app.component.css.shim.ngstyle.js ***!
  \***************************************************/
/*! exports provided: styles */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "styles", function() { return styles; });
/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
var styles = [".container[_ngcontent-%COMP%] {\r\n    box-sizing: border-box;\r\n    position: absolute;\r\n    bottom: 0;\r\n    left: 0;\r\n    width: 100vw;\r\n    height: 33vh;\r\n    background: #fff;\r\n    box-shadow: 0 -10px 8px -8px rgba(0,0,0,0.2);\r\n    z-index: 1;\r\n}\n/*# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbInNyYy9hcHAvYXBwLmNvbXBvbmVudC5jc3MiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IkFBQUE7SUFDSSxzQkFBc0I7SUFDdEIsa0JBQWtCO0lBQ2xCLFNBQVM7SUFDVCxPQUFPO0lBQ1AsWUFBWTtJQUNaLFlBQVk7SUFDWixnQkFBZ0I7SUFDaEIsNENBQTRDO0lBQzVDLFVBQVU7QUFDZCIsImZpbGUiOiJzcmMvYXBwL2FwcC5jb21wb25lbnQuY3NzIiwic291cmNlc0NvbnRlbnQiOlsiLmNvbnRhaW5lciB7XHJcbiAgICBib3gtc2l6aW5nOiBib3JkZXItYm94O1xyXG4gICAgcG9zaXRpb246IGFic29sdXRlO1xyXG4gICAgYm90dG9tOiAwO1xyXG4gICAgbGVmdDogMDtcclxuICAgIHdpZHRoOiAxMDB2dztcclxuICAgIGhlaWdodDogMzN2aDtcclxuICAgIGJhY2tncm91bmQ6ICNmZmY7XHJcbiAgICBib3gtc2hhZG93OiAwIC0xMHB4IDhweCAtOHB4IHJnYmEoMCwwLDAsMC4yKTtcclxuICAgIHotaW5kZXg6IDE7XHJcbn1cclxuIl19 */"];



/***/ }),

/***/ "./src/app/app.component.ngfactory.js":
/*!********************************************!*\
  !*** ./src/app/app.component.ngfactory.js ***!
  \********************************************/
/*! exports provided: RenderType_AppComponent, View_AppComponent_0, View_AppComponent_Host_0, AppComponentNgFactory */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "RenderType_AppComponent", function() { return RenderType_AppComponent; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "View_AppComponent_0", function() { return View_AppComponent_0; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "View_AppComponent_Host_0", function() { return View_AppComponent_Host_0; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "AppComponentNgFactory", function() { return AppComponentNgFactory; });
/* harmony import */ var _app_component_css_shim_ngstyle__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! ./app.component.css.shim.ngstyle */ "./src/app/app.component.css.shim.ngstyle.js");
/* harmony import */ var _angular_core__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! @angular/core */ "./node_modules/@angular/core/fesm5/core.js");
/* harmony import */ var _angular_router__WEBPACK_IMPORTED_MODULE_2__ = __webpack_require__(/*! @angular/router */ "./node_modules/@angular/router/fesm5/router.js");
/* harmony import */ var _app_component__WEBPACK_IMPORTED_MODULE_3__ = __webpack_require__(/*! ./app.component */ "./src/app/app.component.ts");
/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 




var styles_AppComponent = [_app_component_css_shim_ngstyle__WEBPACK_IMPORTED_MODULE_0__["styles"]];
var RenderType_AppComponent = _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵcrt"]({ encapsulation: 0, styles: styles_AppComponent, data: {} });

function View_AppComponent_0(_l) { return _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵvid"](0, [(_l()(), _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵeld"](0, 16777216, null, null, 1, "router-outlet", [], null, null, null, null, null)), _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵdid"](1, 212992, null, 0, _angular_router__WEBPACK_IMPORTED_MODULE_2__["RouterOutlet"], [_angular_router__WEBPACK_IMPORTED_MODULE_2__["ChildrenOutletContexts"], _angular_core__WEBPACK_IMPORTED_MODULE_1__["ViewContainerRef"], _angular_core__WEBPACK_IMPORTED_MODULE_1__["ComponentFactoryResolver"], [8, null], _angular_core__WEBPACK_IMPORTED_MODULE_1__["ChangeDetectorRef"]], null, null)], function (_ck, _v) { _ck(_v, 1, 0); }, null); }
function View_AppComponent_Host_0(_l) { return _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵvid"](0, [(_l()(), _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵeld"](0, 0, null, null, 1, "app-root", [], null, null, null, View_AppComponent_0, RenderType_AppComponent)), _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵdid"](1, 114688, null, 0, _app_component__WEBPACK_IMPORTED_MODULE_3__["AppComponent"], [], null, null)], function (_ck, _v) { _ck(_v, 1, 0); }, null); }
var AppComponentNgFactory = _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵccf"]("app-root", _app_component__WEBPACK_IMPORTED_MODULE_3__["AppComponent"], View_AppComponent_Host_0, {}, {}, []);



/***/ }),

/***/ "./src/app/app.component.ts":
/*!**********************************!*\
  !*** ./src/app/app.component.ts ***!
  \**********************************/
/*! exports provided: AppComponent */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "AppComponent", function() { return AppComponent; });
/* harmony import */ var _angular_core__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! @angular/core */ "./node_modules/@angular/core/fesm5/core.js");

var AppComponent = /** @class */ (function () {
    function AppComponent() {
    }
    AppComponent.prototype.ngOnInit = function () { };
    return AppComponent;
}());



/***/ }),

/***/ "./src/app/app.module.ngfactory.js":
/*!*****************************************!*\
  !*** ./src/app/app.module.ngfactory.js ***!
  \*****************************************/
/*! exports provided: AppModuleNgFactory */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "AppModuleNgFactory", function() { return AppModuleNgFactory; });
/* harmony import */ var _angular_core__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! @angular/core */ "./node_modules/@angular/core/fesm5/core.js");
/* harmony import */ var _app_module__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! ./app.module */ "./src/app/app.module.ts");
/* harmony import */ var _app_component__WEBPACK_IMPORTED_MODULE_2__ = __webpack_require__(/*! ./app.component */ "./src/app/app.component.ts");
/* harmony import */ var _node_modules_angular_router_router_ngfactory__WEBPACK_IMPORTED_MODULE_3__ = __webpack_require__(/*! ../../node_modules/@angular/router/router.ngfactory */ "./node_modules/@angular/router/router.ngfactory.js");
/* harmony import */ var _components_punch_punch_component_ngfactory__WEBPACK_IMPORTED_MODULE_4__ = __webpack_require__(/*! ./components/punch/punch.component.ngfactory */ "./src/app/components/punch/punch.component.ngfactory.js");
/* harmony import */ var _app_component_ngfactory__WEBPACK_IMPORTED_MODULE_5__ = __webpack_require__(/*! ./app.component.ngfactory */ "./src/app/app.component.ngfactory.js");
/* harmony import */ var _angular_common__WEBPACK_IMPORTED_MODULE_6__ = __webpack_require__(/*! @angular/common */ "./node_modules/@angular/common/fesm5/common.js");
/* harmony import */ var _angular_platform_browser__WEBPACK_IMPORTED_MODULE_7__ = __webpack_require__(/*! @angular/platform-browser */ "./node_modules/@angular/platform-browser/fesm5/platform-browser.js");
/* harmony import */ var _services_punch_service__WEBPACK_IMPORTED_MODULE_8__ = __webpack_require__(/*! ./services/punch.service */ "./src/app/services/punch.service.ts");
/* harmony import */ var _angular_router__WEBPACK_IMPORTED_MODULE_9__ = __webpack_require__(/*! @angular/router */ "./node_modules/@angular/router/fesm5/router.js");
/* harmony import */ var _components_punch_punch_module__WEBPACK_IMPORTED_MODULE_10__ = __webpack_require__(/*! ./components/punch/punch.module */ "./src/app/components/punch/punch.module.ts");
/* harmony import */ var _components_punch_punch_component__WEBPACK_IMPORTED_MODULE_11__ = __webpack_require__(/*! ./components/punch/punch.component */ "./src/app/components/punch/punch.component.ts");
/* harmony import */ var _app_routing_module__WEBPACK_IMPORTED_MODULE_12__ = __webpack_require__(/*! ./app-routing.module */ "./src/app/app-routing.module.ts");
/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 













var AppModuleNgFactory = _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵcmf"](_app_module__WEBPACK_IMPORTED_MODULE_1__["AppModule"], [_app_component__WEBPACK_IMPORTED_MODULE_2__["AppComponent"]], function (_l) { return _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵmod"]([_angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵmpd"](512, _angular_core__WEBPACK_IMPORTED_MODULE_0__["ComponentFactoryResolver"], _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵCodegenComponentFactoryResolver"], [[8, [_node_modules_angular_router_router_ngfactory__WEBPACK_IMPORTED_MODULE_3__["ɵEmptyOutletComponentNgFactory"], _components_punch_punch_component_ngfactory__WEBPACK_IMPORTED_MODULE_4__["PunchComponentNgFactory"], _app_component_ngfactory__WEBPACK_IMPORTED_MODULE_5__["AppComponentNgFactory"]]], [3, _angular_core__WEBPACK_IMPORTED_MODULE_0__["ComponentFactoryResolver"]], _angular_core__WEBPACK_IMPORTED_MODULE_0__["NgModuleRef"]]), _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵmpd"](5120, _angular_core__WEBPACK_IMPORTED_MODULE_0__["LOCALE_ID"], _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵangular_packages_core_core_s"], [[3, _angular_core__WEBPACK_IMPORTED_MODULE_0__["LOCALE_ID"]]]), _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵmpd"](4608, _angular_common__WEBPACK_IMPORTED_MODULE_6__["NgLocalization"], _angular_common__WEBPACK_IMPORTED_MODULE_6__["NgLocaleLocalization"], [_angular_core__WEBPACK_IMPORTED_MODULE_0__["LOCALE_ID"], [2, _angular_common__WEBPACK_IMPORTED_MODULE_6__["ɵangular_packages_common_common_a"]]]), _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵmpd"](5120, _angular_core__WEBPACK_IMPORTED_MODULE_0__["APP_ID"], _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵangular_packages_core_core_h"], []), _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵmpd"](5120, _angular_core__WEBPACK_IMPORTED_MODULE_0__["IterableDiffers"], _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵangular_packages_core_core_q"], []), _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵmpd"](5120, _angular_core__WEBPACK_IMPORTED_MODULE_0__["KeyValueDiffers"], _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵangular_packages_core_core_r"], []), _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵmpd"](4608, _angular_platform_browser__WEBPACK_IMPORTED_MODULE_7__["DomSanitizer"], _angular_platform_browser__WEBPACK_IMPORTED_MODULE_7__["ɵDomSanitizerImpl"], [_angular_common__WEBPACK_IMPORTED_MODULE_6__["DOCUMENT"]]), _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵmpd"](6144, _angular_core__WEBPACK_IMPORTED_MODULE_0__["Sanitizer"], null, [_angular_platform_browser__WEBPACK_IMPORTED_MODULE_7__["DomSanitizer"]]), _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵmpd"](4608, _angular_platform_browser__WEBPACK_IMPORTED_MODULE_7__["HAMMER_GESTURE_CONFIG"], _angular_platform_browser__WEBPACK_IMPORTED_MODULE_7__["HammerGestureConfig"], []), _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵmpd"](5120, _angular_platform_browser__WEBPACK_IMPORTED_MODULE_7__["EVENT_MANAGER_PLUGINS"], function (p0_0, p0_1, p0_2, p1_0, p2_0, p2_1, p2_2, p2_3) { return [new _angular_platform_browser__WEBPACK_IMPORTED_MODULE_7__["ɵDomEventsPlugin"](p0_0, p0_1, p0_2), new _angular_platform_browser__WEBPACK_IMPORTED_MODULE_7__["ɵKeyEventsPlugin"](p1_0), new _angular_platform_browser__WEBPACK_IMPORTED_MODULE_7__["ɵHammerGesturesPlugin"](p2_0, p2_1, p2_2, p2_3)]; }, [_angular_common__WEBPACK_IMPORTED_MODULE_6__["DOCUMENT"], _angular_core__WEBPACK_IMPORTED_MODULE_0__["NgZone"], _angular_core__WEBPACK_IMPORTED_MODULE_0__["PLATFORM_ID"], _angular_common__WEBPACK_IMPORTED_MODULE_6__["DOCUMENT"], _angular_common__WEBPACK_IMPORTED_MODULE_6__["DOCUMENT"], _angular_platform_browser__WEBPACK_IMPORTED_MODULE_7__["HAMMER_GESTURE_CONFIG"], _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵConsole"], [2, _angular_platform_browser__WEBPACK_IMPORTED_MODULE_7__["HAMMER_LOADER"]]]), _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵmpd"](4608, _angular_platform_browser__WEBPACK_IMPORTED_MODULE_7__["EventManager"], _angular_platform_browser__WEBPACK_IMPORTED_MODULE_7__["EventManager"], [_angular_platform_browser__WEBPACK_IMPORTED_MODULE_7__["EVENT_MANAGER_PLUGINS"], _angular_core__WEBPACK_IMPORTED_MODULE_0__["NgZone"]]), _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵmpd"](135680, _angular_platform_browser__WEBPACK_IMPORTED_MODULE_7__["ɵDomSharedStylesHost"], _angular_platform_browser__WEBPACK_IMPORTED_MODULE_7__["ɵDomSharedStylesHost"], [_angular_common__WEBPACK_IMPORTED_MODULE_6__["DOCUMENT"]]), _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵmpd"](4608, _angular_platform_browser__WEBPACK_IMPORTED_MODULE_7__["ɵDomRendererFactory2"], _angular_platform_browser__WEBPACK_IMPORTED_MODULE_7__["ɵDomRendererFactory2"], [_angular_platform_browser__WEBPACK_IMPORTED_MODULE_7__["EventManager"], _angular_platform_browser__WEBPACK_IMPORTED_MODULE_7__["ɵDomSharedStylesHost"], _angular_core__WEBPACK_IMPORTED_MODULE_0__["APP_ID"]]), _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵmpd"](6144, _angular_core__WEBPACK_IMPORTED_MODULE_0__["RendererFactory2"], null, [_angular_platform_browser__WEBPACK_IMPORTED_MODULE_7__["ɵDomRendererFactory2"]]), _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵmpd"](6144, _angular_platform_browser__WEBPACK_IMPORTED_MODULE_7__["ɵSharedStylesHost"], null, [_angular_platform_browser__WEBPACK_IMPORTED_MODULE_7__["ɵDomSharedStylesHost"]]), _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵmpd"](4608, _angular_core__WEBPACK_IMPORTED_MODULE_0__["Testability"], _angular_core__WEBPACK_IMPORTED_MODULE_0__["Testability"], [_angular_core__WEBPACK_IMPORTED_MODULE_0__["NgZone"]]), _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵmpd"](4608, _services_punch_service__WEBPACK_IMPORTED_MODULE_8__["PunchService"], _services_punch_service__WEBPACK_IMPORTED_MODULE_8__["PunchService"], []), _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵmpd"](5120, _angular_router__WEBPACK_IMPORTED_MODULE_9__["ActivatedRoute"], _angular_router__WEBPACK_IMPORTED_MODULE_9__["ɵangular_packages_router_router_g"], [_angular_router__WEBPACK_IMPORTED_MODULE_9__["Router"]]), _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵmpd"](4608, _angular_router__WEBPACK_IMPORTED_MODULE_9__["NoPreloading"], _angular_router__WEBPACK_IMPORTED_MODULE_9__["NoPreloading"], []), _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵmpd"](6144, _angular_router__WEBPACK_IMPORTED_MODULE_9__["PreloadingStrategy"], null, [_angular_router__WEBPACK_IMPORTED_MODULE_9__["NoPreloading"]]), _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵmpd"](135680, _angular_router__WEBPACK_IMPORTED_MODULE_9__["RouterPreloader"], _angular_router__WEBPACK_IMPORTED_MODULE_9__["RouterPreloader"], [_angular_router__WEBPACK_IMPORTED_MODULE_9__["Router"], _angular_core__WEBPACK_IMPORTED_MODULE_0__["NgModuleFactoryLoader"], _angular_core__WEBPACK_IMPORTED_MODULE_0__["Compiler"], _angular_core__WEBPACK_IMPORTED_MODULE_0__["Injector"], _angular_router__WEBPACK_IMPORTED_MODULE_9__["PreloadingStrategy"]]), _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵmpd"](4608, _angular_router__WEBPACK_IMPORTED_MODULE_9__["PreloadAllModules"], _angular_router__WEBPACK_IMPORTED_MODULE_9__["PreloadAllModules"], []), _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵmpd"](5120, _angular_router__WEBPACK_IMPORTED_MODULE_9__["ɵangular_packages_router_router_n"], _angular_router__WEBPACK_IMPORTED_MODULE_9__["ɵangular_packages_router_router_c"], [_angular_router__WEBPACK_IMPORTED_MODULE_9__["Router"], _angular_common__WEBPACK_IMPORTED_MODULE_6__["ViewportScroller"], _angular_router__WEBPACK_IMPORTED_MODULE_9__["ROUTER_CONFIGURATION"]]), _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵmpd"](5120, _angular_router__WEBPACK_IMPORTED_MODULE_9__["ROUTER_INITIALIZER"], _angular_router__WEBPACK_IMPORTED_MODULE_9__["ɵangular_packages_router_router_j"], [_angular_router__WEBPACK_IMPORTED_MODULE_9__["ɵangular_packages_router_router_h"]]), _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵmpd"](5120, _angular_core__WEBPACK_IMPORTED_MODULE_0__["APP_BOOTSTRAP_LISTENER"], function (p0_0) { return [p0_0]; }, [_angular_router__WEBPACK_IMPORTED_MODULE_9__["ROUTER_INITIALIZER"]]), _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵmpd"](1073742336, _angular_common__WEBPACK_IMPORTED_MODULE_6__["CommonModule"], _angular_common__WEBPACK_IMPORTED_MODULE_6__["CommonModule"], []), _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵmpd"](1024, _angular_core__WEBPACK_IMPORTED_MODULE_0__["ErrorHandler"], _angular_platform_browser__WEBPACK_IMPORTED_MODULE_7__["ɵangular_packages_platform_browser_platform_browser_a"], []), _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵmpd"](1024, _angular_core__WEBPACK_IMPORTED_MODULE_0__["NgProbeToken"], function () { return [_angular_router__WEBPACK_IMPORTED_MODULE_9__["ɵangular_packages_router_router_b"]()]; }, []), _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵmpd"](512, _angular_router__WEBPACK_IMPORTED_MODULE_9__["ɵangular_packages_router_router_h"], _angular_router__WEBPACK_IMPORTED_MODULE_9__["ɵangular_packages_router_router_h"], [_angular_core__WEBPACK_IMPORTED_MODULE_0__["Injector"]]), _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵmpd"](1024, _angular_core__WEBPACK_IMPORTED_MODULE_0__["APP_INITIALIZER"], function (p0_0, p1_0) { return [_angular_platform_browser__WEBPACK_IMPORTED_MODULE_7__["ɵangular_packages_platform_browser_platform_browser_j"](p0_0), _angular_router__WEBPACK_IMPORTED_MODULE_9__["ɵangular_packages_router_router_i"](p1_0)]; }, [[2, _angular_core__WEBPACK_IMPORTED_MODULE_0__["NgProbeToken"]], _angular_router__WEBPACK_IMPORTED_MODULE_9__["ɵangular_packages_router_router_h"]]), _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵmpd"](512, _angular_core__WEBPACK_IMPORTED_MODULE_0__["ApplicationInitStatus"], _angular_core__WEBPACK_IMPORTED_MODULE_0__["ApplicationInitStatus"], [[2, _angular_core__WEBPACK_IMPORTED_MODULE_0__["APP_INITIALIZER"]]]), _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵmpd"](131584, _angular_core__WEBPACK_IMPORTED_MODULE_0__["ApplicationRef"], _angular_core__WEBPACK_IMPORTED_MODULE_0__["ApplicationRef"], [_angular_core__WEBPACK_IMPORTED_MODULE_0__["NgZone"], _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵConsole"], _angular_core__WEBPACK_IMPORTED_MODULE_0__["Injector"], _angular_core__WEBPACK_IMPORTED_MODULE_0__["ErrorHandler"], _angular_core__WEBPACK_IMPORTED_MODULE_0__["ComponentFactoryResolver"], _angular_core__WEBPACK_IMPORTED_MODULE_0__["ApplicationInitStatus"]]), _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵmpd"](1073742336, _angular_core__WEBPACK_IMPORTED_MODULE_0__["ApplicationModule"], _angular_core__WEBPACK_IMPORTED_MODULE_0__["ApplicationModule"], [_angular_core__WEBPACK_IMPORTED_MODULE_0__["ApplicationRef"]]), _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵmpd"](1073742336, _angular_platform_browser__WEBPACK_IMPORTED_MODULE_7__["BrowserModule"], _angular_platform_browser__WEBPACK_IMPORTED_MODULE_7__["BrowserModule"], [[3, _angular_platform_browser__WEBPACK_IMPORTED_MODULE_7__["BrowserModule"]]]), _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵmpd"](1073742336, _components_punch_punch_module__WEBPACK_IMPORTED_MODULE_10__["PunchModule"], _components_punch_punch_module__WEBPACK_IMPORTED_MODULE_10__["PunchModule"], []), _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵmpd"](1024, _angular_router__WEBPACK_IMPORTED_MODULE_9__["ɵangular_packages_router_router_a"], _angular_router__WEBPACK_IMPORTED_MODULE_9__["ɵangular_packages_router_router_e"], [[3, _angular_router__WEBPACK_IMPORTED_MODULE_9__["Router"]]]), _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵmpd"](512, _angular_router__WEBPACK_IMPORTED_MODULE_9__["UrlSerializer"], _angular_router__WEBPACK_IMPORTED_MODULE_9__["DefaultUrlSerializer"], []), _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵmpd"](512, _angular_router__WEBPACK_IMPORTED_MODULE_9__["ChildrenOutletContexts"], _angular_router__WEBPACK_IMPORTED_MODULE_9__["ChildrenOutletContexts"], []), _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵmpd"](256, _angular_router__WEBPACK_IMPORTED_MODULE_9__["ROUTER_CONFIGURATION"], {}, []), _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵmpd"](1024, _angular_common__WEBPACK_IMPORTED_MODULE_6__["LocationStrategy"], _angular_router__WEBPACK_IMPORTED_MODULE_9__["ɵangular_packages_router_router_d"], [_angular_common__WEBPACK_IMPORTED_MODULE_6__["PlatformLocation"], [2, _angular_common__WEBPACK_IMPORTED_MODULE_6__["APP_BASE_HREF"]], _angular_router__WEBPACK_IMPORTED_MODULE_9__["ROUTER_CONFIGURATION"]]), _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵmpd"](512, _angular_common__WEBPACK_IMPORTED_MODULE_6__["Location"], _angular_common__WEBPACK_IMPORTED_MODULE_6__["Location"], [_angular_common__WEBPACK_IMPORTED_MODULE_6__["LocationStrategy"]]), _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵmpd"](512, _angular_core__WEBPACK_IMPORTED_MODULE_0__["Compiler"], _angular_core__WEBPACK_IMPORTED_MODULE_0__["Compiler"], []), _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵmpd"](512, _angular_core__WEBPACK_IMPORTED_MODULE_0__["NgModuleFactoryLoader"], _angular_core__WEBPACK_IMPORTED_MODULE_0__["SystemJsNgModuleLoader"], [_angular_core__WEBPACK_IMPORTED_MODULE_0__["Compiler"], [2, _angular_core__WEBPACK_IMPORTED_MODULE_0__["SystemJsNgModuleLoaderConfig"]]]), _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵmpd"](1024, _angular_router__WEBPACK_IMPORTED_MODULE_9__["ROUTES"], function () { return [[{ path: "punch-list", component: _components_punch_punch_component__WEBPACK_IMPORTED_MODULE_11__["PunchComponent"] }, { path: "punch-list/:trade", component: _components_punch_punch_component__WEBPACK_IMPORTED_MODULE_11__["PunchComponent"] }, { path: "", component: _app_component__WEBPACK_IMPORTED_MODULE_2__["AppComponent"] }]]; }, []), _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵmpd"](1024, _angular_router__WEBPACK_IMPORTED_MODULE_9__["Router"], _angular_router__WEBPACK_IMPORTED_MODULE_9__["ɵangular_packages_router_router_f"], [_angular_core__WEBPACK_IMPORTED_MODULE_0__["ApplicationRef"], _angular_router__WEBPACK_IMPORTED_MODULE_9__["UrlSerializer"], _angular_router__WEBPACK_IMPORTED_MODULE_9__["ChildrenOutletContexts"], _angular_common__WEBPACK_IMPORTED_MODULE_6__["Location"], _angular_core__WEBPACK_IMPORTED_MODULE_0__["Injector"], _angular_core__WEBPACK_IMPORTED_MODULE_0__["NgModuleFactoryLoader"], _angular_core__WEBPACK_IMPORTED_MODULE_0__["Compiler"], _angular_router__WEBPACK_IMPORTED_MODULE_9__["ROUTES"], _angular_router__WEBPACK_IMPORTED_MODULE_9__["ROUTER_CONFIGURATION"], [2, _angular_router__WEBPACK_IMPORTED_MODULE_9__["UrlHandlingStrategy"]], [2, _angular_router__WEBPACK_IMPORTED_MODULE_9__["RouteReuseStrategy"]]]), _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵmpd"](1073742336, _angular_router__WEBPACK_IMPORTED_MODULE_9__["RouterModule"], _angular_router__WEBPACK_IMPORTED_MODULE_9__["RouterModule"], [[2, _angular_router__WEBPACK_IMPORTED_MODULE_9__["ɵangular_packages_router_router_a"]], [2, _angular_router__WEBPACK_IMPORTED_MODULE_9__["Router"]]]), _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵmpd"](1073742336, _app_routing_module__WEBPACK_IMPORTED_MODULE_12__["AppRoutingModule"], _app_routing_module__WEBPACK_IMPORTED_MODULE_12__["AppRoutingModule"], []), _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵmpd"](1073742336, _app_module__WEBPACK_IMPORTED_MODULE_1__["AppModule"], _app_module__WEBPACK_IMPORTED_MODULE_1__["AppModule"], []), _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵmpd"](256, _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵAPP_ROOT"], true, [])]); });



/***/ }),

/***/ "./src/app/app.module.ts":
/*!*******************************!*\
  !*** ./src/app/app.module.ts ***!
  \*******************************/
/*! exports provided: AppModule */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "AppModule", function() { return AppModule; });
var AppModule = /** @class */ (function () {
    function AppModule() {
    }
    return AppModule;
}());



/***/ }),

/***/ "./src/app/components/map/map.component.css.shim.ngstyle.js":
/*!******************************************************************!*\
  !*** ./src/app/components/map/map.component.css.shim.ngstyle.js ***!
  \******************************************************************/
/*! exports provided: styles */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "styles", function() { return styles; });
/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
var styles = [".map[_ngcontent-%COMP%] {\r\n    width: 100vw;\r\n    height: 67vh;\r\n}\n/*# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbInNyYy9hcHAvY29tcG9uZW50cy9tYXAvbWFwLmNvbXBvbmVudC5jc3MiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IkFBQUE7SUFDSSxZQUFZO0lBQ1osWUFBWTtBQUNoQiIsImZpbGUiOiJzcmMvYXBwL2NvbXBvbmVudHMvbWFwL21hcC5jb21wb25lbnQuY3NzIiwic291cmNlc0NvbnRlbnQiOlsiLm1hcCB7XHJcbiAgICB3aWR0aDogMTAwdnc7XHJcbiAgICBoZWlnaHQ6IDY3dmg7XHJcbn0iXX0= */"];



/***/ }),

/***/ "./src/app/components/map/map.component.ngfactory.js":
/*!***********************************************************!*\
  !*** ./src/app/components/map/map.component.ngfactory.js ***!
  \***********************************************************/
/*! exports provided: RenderType_MapComponent, View_MapComponent_0, View_MapComponent_Host_0, MapComponentNgFactory */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "RenderType_MapComponent", function() { return RenderType_MapComponent; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "View_MapComponent_0", function() { return View_MapComponent_0; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "View_MapComponent_Host_0", function() { return View_MapComponent_Host_0; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "MapComponentNgFactory", function() { return MapComponentNgFactory; });
/* harmony import */ var _map_component_css_shim_ngstyle__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! ./map.component.css.shim.ngstyle */ "./src/app/components/map/map.component.css.shim.ngstyle.js");
/* harmony import */ var _angular_core__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! @angular/core */ "./node_modules/@angular/core/fesm5/core.js");
/* harmony import */ var _services_mapbox_service__WEBPACK_IMPORTED_MODULE_2__ = __webpack_require__(/*! ../../services/mapbox.service */ "./src/app/services/mapbox.service.ts");
/* harmony import */ var _map_component__WEBPACK_IMPORTED_MODULE_3__ = __webpack_require__(/*! ./map.component */ "./src/app/components/map/map.component.ts");
/* harmony import */ var _services_punch_service__WEBPACK_IMPORTED_MODULE_4__ = __webpack_require__(/*! ../../services/punch.service */ "./src/app/services/punch.service.ts");
/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 





var styles_MapComponent = [_map_component_css_shim_ngstyle__WEBPACK_IMPORTED_MODULE_0__["styles"]];
var RenderType_MapComponent = _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵcrt"]({ encapsulation: 0, styles: styles_MapComponent, data: {} });

function View_MapComponent_0(_l) { return _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵvid"](0, [(_l()(), _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵeld"](0, 0, null, null, 0, "div", [["class", "map"], ["id", "map"]], null, null, null, null, null))], null, null); }
function View_MapComponent_Host_0(_l) { return _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵvid"](0, [(_l()(), _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵeld"](0, 0, null, null, 2, "map-box", [], null, null, null, View_MapComponent_0, RenderType_MapComponent)), _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵprd"](512, null, _services_mapbox_service__WEBPACK_IMPORTED_MODULE_2__["MapboxService"], _services_mapbox_service__WEBPACK_IMPORTED_MODULE_2__["MapboxService"], []), _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵdid"](2, 114688, null, 0, _map_component__WEBPACK_IMPORTED_MODULE_3__["MapComponent"], [_services_mapbox_service__WEBPACK_IMPORTED_MODULE_2__["MapboxService"], _services_punch_service__WEBPACK_IMPORTED_MODULE_4__["PunchService"]], null, null)], function (_ck, _v) { _ck(_v, 2, 0); }, null); }
var MapComponentNgFactory = _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵccf"]("map-box", _map_component__WEBPACK_IMPORTED_MODULE_3__["MapComponent"], View_MapComponent_Host_0, { punchToFlyTo: "punchCoords" }, {}, []);



/***/ }),

/***/ "./src/app/components/map/map.component.ts":
/*!*************************************************!*\
  !*** ./src/app/components/map/map.component.ts ***!
  \*************************************************/
/*! exports provided: MapComponent */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "MapComponent", function() { return MapComponent; });
/* harmony import */ var _angular_core__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! @angular/core */ "./node_modules/@angular/core/fesm5/core.js");
/* harmony import */ var _services_mapbox_service__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! ../../services/mapbox.service */ "./src/app/services/mapbox.service.ts");
/* harmony import */ var _services_punch_service__WEBPACK_IMPORTED_MODULE_2__ = __webpack_require__(/*! ../../services/punch.service */ "./src/app/services/punch.service.ts");
/* harmony import */ var _models_punch__WEBPACK_IMPORTED_MODULE_3__ = __webpack_require__(/*! ../../models/punch */ "./src/app/models/punch.ts");
/* harmony import */ var _models_geojson__WEBPACK_IMPORTED_MODULE_4__ = __webpack_require__(/*! ../../models/geojson */ "./src/app/models/geojson.ts");
/* harmony import */ var mapbox_gl__WEBPACK_IMPORTED_MODULE_5__ = __webpack_require__(/*! mapbox-gl */ "./node_modules/mapbox-gl/dist/mapbox-gl.js");
/* harmony import */ var mapbox_gl__WEBPACK_IMPORTED_MODULE_5___default = /*#__PURE__*/__webpack_require__.n(mapbox_gl__WEBPACK_IMPORTED_MODULE_5__);






var MapComponent = /** @class */ (function () {
    function MapComponent(_mapServ, _punchServ) {
        this._mapServ = _mapServ;
        this._punchServ = _punchServ;
        this.mapStyle = 'mapbox://styles/erqwork/cjvfvyv2ehrjb1fs3v0at0vvz';
        this.mapStart = [-96.932107, 32.643821];
    }
    MapComponent.prototype.ngOnInit = function () {
        this.markers = this.createMarkersFromPunch();
        this.mapInit();
    };
    MapComponent.prototype.createMarkersFromPunch = function () {
        this.punches = this._punchServ.punchList;
        var featurePunchArr = [];
        this.punches.forEach(function (punch) {
            var tempMarker = new _models_geojson__WEBPACK_IMPORTED_MODULE_4__["GeoJson"]([punch.long, punch.lat], { message: punch.task, punch: punch });
            featurePunchArr.push(tempMarker);
        });
        return featurePunchArr;
    };
    MapComponent.prototype.mapInit = function () {
        var _this = this;
        this.map = new mapbox_gl__WEBPACK_IMPORTED_MODULE_5__["Map"]({
            container: 'map',
            style: this.mapStyle,
            center: this.mapStart,
            zoom: 16
        });
        this.map.addControl(new mapbox_gl__WEBPACK_IMPORTED_MODULE_5__["NavigationControl"]());
        this.map.on('load', function (event) {
            // register source
            _this.map.addSource('punchmap', {
                type: 'geojson',
                data: {
                    type: 'FeatureCollection',
                    features: []
                }
            });
            // get and set source
            _this.source = _this.map.getSource('punchmap');
            var data = new _models_geojson__WEBPACK_IMPORTED_MODULE_4__["FeatureCollection"](_this.markers);
            _this.source.setData(data);
            // create map layer
            _this.map.addLayer({
                id: 'punchmap',
                source: 'punchmap',
                type: 'symbol',
                layout: {
                    'text-field': '{message}',
                    'text-size': 24,
                    'icon-image': 'hardware-15',
                    'text-offset': [0, 1.5]
                },
                paint: {
                    'text-color': '#1c75df',
                    'text-halo-color': '#fff',
                    'text-halo-width': 2
                }
            });
            _this.map.on('click', function (event) {
                var features = _this.map.queryRenderedFeatures(event.point, { layers: ['punchmap'] });
                if (!features.length) {
                    return;
                }
                var feature = features[0];
                var parsedFeat = JSON.parse(feature.properties.punch);
                var selectedNow = _this._punchServ.getSelectedId();
                _this._punchServ.punchList.find(function (p) { return p.id == selectedNow; }).selected = '';
                _this._punchServ.punchList.find(function (p) { return p.id === parsedFeat.id; }).selected = 'selected';
                _this.flyTo(feature);
            });
            _this.map.on('mousemove', function (event) {
                var features = _this.map.queryRenderedFeatures(event.point, { layers: ['punchmap'] });
                _this.map.getCanvas().style.cursor = (features.length) ? 'pointer' : '';
            });
        });
    };
    MapComponent.prototype.flyTo = function (data) {
        this.map.flyTo({
            center: data.geometry.coordinates,
            zoom: 16
        });
    };
    MapComponent.prototype.clickedFlyTo = function (punchCoords) {
        this.map.flyTo({
            center: punchCoords,
            zoom: 16
        });
    };
    return MapComponent;
}());



/***/ }),

/***/ "./src/app/components/punch/punch.component.css.shim.ngstyle.js":
/*!**********************************************************************!*\
  !*** ./src/app/components/punch/punch.component.css.shim.ngstyle.js ***!
  \**********************************************************************/
/*! exports provided: styles */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "styles", function() { return styles; });
/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
var styles = [".flex-punch[_ngcontent-%COMP%] {\r\n    display: flex;\r\n    flex-flow: row nowrap;\r\n    justify-content: flex-start;\r\n    align-content: center;\r\n    height: 33vh;\r\n}\r\n\r\n.flex-punch[_ngcontent-%COMP%]   *[_ngcontent-%COMP%] {\r\n    box-sizing: border-box;\r\n}\r\n\r\n.flex-punch[_ngcontent-%COMP%]   button[_ngcontent-%COMP%] {\r\n    display: block;\r\n    background: #1c75df;\r\n    color: #eaf4ff;\r\n    font-size: 1rem;\r\n    border: 0;\r\n    flex-basis: 4%;\r\n    cursor: pointer;\r\n}\r\n\r\n.flex-punch[_ngcontent-%COMP%]   button[_ngcontent-%COMP%]:active {\r\n    background: #1363c5;\r\n    box-shadow: inset 4px 4px 2px -1px rgba(0, 0, 0, 0.2);\r\n    outline: 0;\r\n}\r\n\r\n.punch[_ngcontent-%COMP%] {\r\n    display: none;\r\n    background: radial-gradient(circle, #2d96ff 80%, #1c75df);\r\n    color: #eaf4ff;\r\n    width: 100%;\r\n    padding: 1vw;\r\n    box-sizing: border-box;\r\n}\r\n\r\n.punch.selected[_ngcontent-%COMP%] {\r\n    display: block;\r\n}\r\n\r\n.taskHeader[_ngcontent-%COMP%] {\r\n    font-size: 2rem;\r\n    display: inline;\r\n}\r\n\r\n.taskHeader[_ngcontent-%COMP%]:hover {\r\n    text-decoration: underline;\r\n    cursor: pointer;\r\n}\r\n\r\n.severity[_ngcontent-%COMP%]:hover {\r\n    text-decoration: none;\r\n    cursor: default;\r\n}\r\n\r\n.taskHeader[_ngcontent-%COMP%]   .severity[_ngcontent-%COMP%] {\r\n    font-size: 0.75rem;\r\n    vertical-align: middle;\r\n    padding: 0.2vw 2vw;\r\n}\r\n\r\n.taskHeader[_ngcontent-%COMP%]   .severity.high[_ngcontent-%COMP%] {\r\n    background: red;\r\n    border-radius: 6px;\r\n}\r\n\r\n.stateDue[_ngcontent-%COMP%] {\r\n    display: flex;\r\n    flex-flow: row nowrap;\r\n    font-size: 0.75rem;\r\n    margin: 0.4vw 0;\r\n}\r\n\r\n.taskState[_ngcontent-%COMP%] {\r\n    margin-right: 1vw;\r\n    padding: 0.5vw 1vw;\r\n}\r\n\r\n.dueDate[_ngcontent-%COMP%] {\r\n    padding: 0.5vw 1vw;\r\n}\r\n\r\n.blocked[_ngcontent-%COMP%] {\r\n    background: red;\r\n    border-radius: 6px;\r\n}\r\n\r\n.in.progress[_ngcontent-%COMP%] {\r\n    text-shadow: 2px 2px 1px rgba(0, 0, 0, 0.2);\r\n    padding-left: 0;\r\n}\r\n\r\n.complete[_ngcontent-%COMP%] {\r\n    background: green;\r\n    border-radius: 6px;\r\n}\r\n\r\n.createdBy[_ngcontent-%COMP%] {\r\n    font-size: 0.5rem;\r\n    line-height: 2;\r\n}\r\n\r\n.no-trade[_ngcontent-%COMP%] {\r\n    display: flex;\r\n    flex-flow: column wrap;\r\n    justify-content: center;\r\n    align-items: center;\r\n    height: 100%;\r\n    background: radial-gradient(circle, #2d96ff 80%, #1c75df);\r\n    color: #eaf4ff;\r\n    height: 33vh;\r\n}\r\n\r\n@media screen and (max-width: 768px) {\r\n    .flex-punch[_ngcontent-%COMP%]   button[_ngcontent-%COMP%] {\r\n        flex-basis: 10%;\r\n        font-size: 4rem;\r\n    }\r\n    .punch[_ngcontent-%COMP%]   h2[_ngcontent-%COMP%] {\r\n        font-size: 3.6rem;\r\n    }\r\n    .punch[_ngcontent-%COMP%]   h2[_ngcontent-%COMP%]   .severity[_ngcontent-%COMP%] {\r\n        font-size: 1.25rem;\r\n    }\r\n\r\n    .createdBy[_ngcontent-%COMP%] {\r\n        font-size: 1.5rem;\r\n    }\r\n\r\n    .worker[_ngcontent-%COMP%] {\r\n        font-size: 2.5rem;\r\n    }\r\n\r\n    .stateDue[_ngcontent-%COMP%] {\r\n        font-size: 2rem;\r\n    }\r\n}\n/*# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbInNyYy9hcHAvY29tcG9uZW50cy9wdW5jaC9wdW5jaC5jb21wb25lbnQuY3NzIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiJBQUFBO0lBQ0ksYUFBYTtJQUNiLHFCQUFxQjtJQUNyQiwyQkFBMkI7SUFDM0IscUJBQXFCO0lBQ3JCLFlBQVk7QUFDaEI7O0FBRUE7SUFDSSxzQkFBc0I7QUFDMUI7O0FBRUE7SUFDSSxjQUFjO0lBQ2QsbUJBQW1CO0lBQ25CLGNBQWM7SUFDZCxlQUFlO0lBQ2YsU0FBUztJQUNULGNBQWM7SUFDZCxlQUFlO0FBQ25COztBQUVBO0lBQ0ksbUJBQW1CO0lBQ25CLHFEQUFxRDtJQUNyRCxVQUFVO0FBQ2Q7O0FBRUE7SUFDSSxhQUFhO0lBQ2IseURBQXlEO0lBQ3pELGNBQWM7SUFDZCxXQUFXO0lBQ1gsWUFBWTtJQUNaLHNCQUFzQjtBQUMxQjs7QUFFQTtJQUNJLGNBQWM7QUFDbEI7O0FBRUE7SUFDSSxlQUFlO0lBQ2YsZUFBZTtBQUNuQjs7QUFFQTtJQUNJLDBCQUEwQjtJQUMxQixlQUFlO0FBQ25COztBQUVBO0lBQ0kscUJBQXFCO0lBQ3JCLGVBQWU7QUFDbkI7O0FBRUE7SUFDSSxrQkFBa0I7SUFDbEIsc0JBQXNCO0lBQ3RCLGtCQUFrQjtBQUN0Qjs7QUFFQTtJQUNJLGVBQWU7SUFDZixrQkFBa0I7QUFDdEI7O0FBRUE7SUFDSSxhQUFhO0lBQ2IscUJBQXFCO0lBQ3JCLGtCQUFrQjtJQUNsQixlQUFlO0FBQ25COztBQUVBO0lBQ0ksaUJBQWlCO0lBQ2pCLGtCQUFrQjtBQUN0Qjs7QUFFQTtJQUNJLGtCQUFrQjtBQUN0Qjs7QUFFQTtJQUNJLGVBQWU7SUFDZixrQkFBa0I7QUFDdEI7O0FBRUE7SUFDSSwyQ0FBMkM7SUFDM0MsZUFBZTtBQUNuQjs7QUFFQTtJQUNJLGlCQUFpQjtJQUNqQixrQkFBa0I7QUFDdEI7O0FBRUE7SUFDSSxpQkFBaUI7SUFDakIsY0FBYztBQUNsQjs7QUFFQTtJQUNJLGFBQWE7SUFDYixzQkFBc0I7SUFDdEIsdUJBQXVCO0lBQ3ZCLG1CQUFtQjtJQUNuQixZQUFZO0lBQ1oseURBQXlEO0lBQ3pELGNBQWM7SUFDZCxZQUFZO0FBQ2hCOztBQUVBO0lBQ0k7UUFDSSxlQUFlO1FBQ2YsZUFBZTtJQUNuQjtJQUNBO1FBQ0ksaUJBQWlCO0lBQ3JCO0lBQ0E7UUFDSSxrQkFBa0I7SUFDdEI7O0lBRUE7UUFDSSxpQkFBaUI7SUFDckI7O0lBRUE7UUFDSSxpQkFBaUI7SUFDckI7O0lBRUE7UUFDSSxlQUFlO0lBQ25CO0FBQ0oiLCJmaWxlIjoic3JjL2FwcC9jb21wb25lbnRzL3B1bmNoL3B1bmNoLmNvbXBvbmVudC5jc3MiLCJzb3VyY2VzQ29udGVudCI6WyIuZmxleC1wdW5jaCB7XHJcbiAgICBkaXNwbGF5OiBmbGV4O1xyXG4gICAgZmxleC1mbG93OiByb3cgbm93cmFwO1xyXG4gICAganVzdGlmeS1jb250ZW50OiBmbGV4LXN0YXJ0O1xyXG4gICAgYWxpZ24tY29udGVudDogY2VudGVyO1xyXG4gICAgaGVpZ2h0OiAzM3ZoO1xyXG59XHJcblxyXG4uZmxleC1wdW5jaCAqIHtcclxuICAgIGJveC1zaXppbmc6IGJvcmRlci1ib3g7XHJcbn1cclxuXHJcbi5mbGV4LXB1bmNoIGJ1dHRvbiB7XHJcbiAgICBkaXNwbGF5OiBibG9jaztcclxuICAgIGJhY2tncm91bmQ6ICMxYzc1ZGY7XHJcbiAgICBjb2xvcjogI2VhZjRmZjtcclxuICAgIGZvbnQtc2l6ZTogMXJlbTtcclxuICAgIGJvcmRlcjogMDtcclxuICAgIGZsZXgtYmFzaXM6IDQlO1xyXG4gICAgY3Vyc29yOiBwb2ludGVyO1xyXG59XHJcblxyXG4uZmxleC1wdW5jaCBidXR0b246YWN0aXZlIHtcclxuICAgIGJhY2tncm91bmQ6ICMxMzYzYzU7XHJcbiAgICBib3gtc2hhZG93OiBpbnNldCA0cHggNHB4IDJweCAtMXB4IHJnYmEoMCwgMCwgMCwgMC4yKTtcclxuICAgIG91dGxpbmU6IDA7XHJcbn1cclxuXHJcbi5wdW5jaCB7XHJcbiAgICBkaXNwbGF5OiBub25lO1xyXG4gICAgYmFja2dyb3VuZDogcmFkaWFsLWdyYWRpZW50KGNpcmNsZSwgIzJkOTZmZiA4MCUsICMxYzc1ZGYpO1xyXG4gICAgY29sb3I6ICNlYWY0ZmY7XHJcbiAgICB3aWR0aDogMTAwJTtcclxuICAgIHBhZGRpbmc6IDF2dztcclxuICAgIGJveC1zaXppbmc6IGJvcmRlci1ib3g7XHJcbn1cclxuXHJcbi5wdW5jaC5zZWxlY3RlZCB7XHJcbiAgICBkaXNwbGF5OiBibG9jaztcclxufVxyXG5cclxuLnRhc2tIZWFkZXIge1xyXG4gICAgZm9udC1zaXplOiAycmVtO1xyXG4gICAgZGlzcGxheTogaW5saW5lO1xyXG59XHJcblxyXG4udGFza0hlYWRlcjpob3ZlciB7XHJcbiAgICB0ZXh0LWRlY29yYXRpb246IHVuZGVybGluZTtcclxuICAgIGN1cnNvcjogcG9pbnRlcjtcclxufVxyXG5cclxuLnNldmVyaXR5OmhvdmVyIHtcclxuICAgIHRleHQtZGVjb3JhdGlvbjogbm9uZTtcclxuICAgIGN1cnNvcjogZGVmYXVsdDtcclxufVxyXG5cclxuLnRhc2tIZWFkZXIgLnNldmVyaXR5IHtcclxuICAgIGZvbnQtc2l6ZTogMC43NXJlbTtcclxuICAgIHZlcnRpY2FsLWFsaWduOiBtaWRkbGU7XHJcbiAgICBwYWRkaW5nOiAwLjJ2dyAydnc7XHJcbn1cclxuXHJcbi50YXNrSGVhZGVyIC5zZXZlcml0eS5oaWdoIHtcclxuICAgIGJhY2tncm91bmQ6IHJlZDtcclxuICAgIGJvcmRlci1yYWRpdXM6IDZweDtcclxufVxyXG5cclxuLnN0YXRlRHVlIHtcclxuICAgIGRpc3BsYXk6IGZsZXg7XHJcbiAgICBmbGV4LWZsb3c6IHJvdyBub3dyYXA7XHJcbiAgICBmb250LXNpemU6IDAuNzVyZW07XHJcbiAgICBtYXJnaW46IDAuNHZ3IDA7XHJcbn1cclxuXHJcbi50YXNrU3RhdGUge1xyXG4gICAgbWFyZ2luLXJpZ2h0OiAxdnc7XHJcbiAgICBwYWRkaW5nOiAwLjV2dyAxdnc7XHJcbn1cclxuXHJcbi5kdWVEYXRlIHtcclxuICAgIHBhZGRpbmc6IDAuNXZ3IDF2dztcclxufVxyXG5cclxuLmJsb2NrZWQge1xyXG4gICAgYmFja2dyb3VuZDogcmVkO1xyXG4gICAgYm9yZGVyLXJhZGl1czogNnB4O1xyXG59XHJcblxyXG4uaW4ucHJvZ3Jlc3Mge1xyXG4gICAgdGV4dC1zaGFkb3c6IDJweCAycHggMXB4IHJnYmEoMCwgMCwgMCwgMC4yKTtcclxuICAgIHBhZGRpbmctbGVmdDogMDtcclxufVxyXG5cclxuLmNvbXBsZXRlIHtcclxuICAgIGJhY2tncm91bmQ6IGdyZWVuO1xyXG4gICAgYm9yZGVyLXJhZGl1czogNnB4O1xyXG59XHJcblxyXG4uY3JlYXRlZEJ5IHtcclxuICAgIGZvbnQtc2l6ZTogMC41cmVtO1xyXG4gICAgbGluZS1oZWlnaHQ6IDI7XHJcbn1cclxuXHJcbi5uby10cmFkZSB7XHJcbiAgICBkaXNwbGF5OiBmbGV4O1xyXG4gICAgZmxleC1mbG93OiBjb2x1bW4gd3JhcDtcclxuICAgIGp1c3RpZnktY29udGVudDogY2VudGVyO1xyXG4gICAgYWxpZ24taXRlbXM6IGNlbnRlcjtcclxuICAgIGhlaWdodDogMTAwJTtcclxuICAgIGJhY2tncm91bmQ6IHJhZGlhbC1ncmFkaWVudChjaXJjbGUsICMyZDk2ZmYgODAlLCAjMWM3NWRmKTtcclxuICAgIGNvbG9yOiAjZWFmNGZmO1xyXG4gICAgaGVpZ2h0OiAzM3ZoO1xyXG59XHJcblxyXG5AbWVkaWEgc2NyZWVuIGFuZCAobWF4LXdpZHRoOiA3NjhweCkge1xyXG4gICAgLmZsZXgtcHVuY2ggYnV0dG9uIHtcclxuICAgICAgICBmbGV4LWJhc2lzOiAxMCU7XHJcbiAgICAgICAgZm9udC1zaXplOiA0cmVtO1xyXG4gICAgfVxyXG4gICAgLnB1bmNoIGgyIHtcclxuICAgICAgICBmb250LXNpemU6IDMuNnJlbTtcclxuICAgIH1cclxuICAgIC5wdW5jaCBoMiAuc2V2ZXJpdHkge1xyXG4gICAgICAgIGZvbnQtc2l6ZTogMS4yNXJlbTtcclxuICAgIH1cclxuXHJcbiAgICAuY3JlYXRlZEJ5IHtcclxuICAgICAgICBmb250LXNpemU6IDEuNXJlbTtcclxuICAgIH1cclxuXHJcbiAgICAud29ya2VyIHtcclxuICAgICAgICBmb250LXNpemU6IDIuNXJlbTtcclxuICAgIH1cclxuXHJcbiAgICAuc3RhdGVEdWUge1xyXG4gICAgICAgIGZvbnQtc2l6ZTogMnJlbTtcclxuICAgIH1cclxufSJdfQ== */"];



/***/ }),

/***/ "./src/app/components/punch/punch.component.ngfactory.js":
/*!***************************************************************!*\
  !*** ./src/app/components/punch/punch.component.ngfactory.js ***!
  \***************************************************************/
/*! exports provided: RenderType_PunchComponent, View_PunchComponent_0, View_PunchComponent_Host_0, PunchComponentNgFactory */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "RenderType_PunchComponent", function() { return RenderType_PunchComponent; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "View_PunchComponent_0", function() { return View_PunchComponent_0; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "View_PunchComponent_Host_0", function() { return View_PunchComponent_Host_0; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "PunchComponentNgFactory", function() { return PunchComponentNgFactory; });
/* harmony import */ var _punch_component_css_shim_ngstyle__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! ./punch.component.css.shim.ngstyle */ "./src/app/components/punch/punch.component.css.shim.ngstyle.js");
/* harmony import */ var _angular_core__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! @angular/core */ "./node_modules/@angular/core/fesm5/core.js");
/* harmony import */ var _angular_common__WEBPACK_IMPORTED_MODULE_2__ = __webpack_require__(/*! @angular/common */ "./node_modules/@angular/common/fesm5/common.js");
/* harmony import */ var _map_map_component_ngfactory__WEBPACK_IMPORTED_MODULE_3__ = __webpack_require__(/*! ../map/map.component.ngfactory */ "./src/app/components/map/map.component.ngfactory.js");
/* harmony import */ var _services_mapbox_service__WEBPACK_IMPORTED_MODULE_4__ = __webpack_require__(/*! ../../services/mapbox.service */ "./src/app/services/mapbox.service.ts");
/* harmony import */ var _map_map_component__WEBPACK_IMPORTED_MODULE_5__ = __webpack_require__(/*! ../map/map.component */ "./src/app/components/map/map.component.ts");
/* harmony import */ var _services_punch_service__WEBPACK_IMPORTED_MODULE_6__ = __webpack_require__(/*! ../../services/punch.service */ "./src/app/services/punch.service.ts");
/* harmony import */ var _punch_component__WEBPACK_IMPORTED_MODULE_7__ = __webpack_require__(/*! ./punch.component */ "./src/app/components/punch/punch.component.ts");
/* harmony import */ var _angular_router__WEBPACK_IMPORTED_MODULE_8__ = __webpack_require__(/*! @angular/router */ "./node_modules/@angular/router/fesm5/router.js");
/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 









var styles_PunchComponent = [_punch_component_css_shim_ngstyle__WEBPACK_IMPORTED_MODULE_0__["styles"]];
var RenderType_PunchComponent = _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵcrt"]({ encapsulation: 0, styles: styles_PunchComponent, data: {} });

function View_PunchComponent_2(_l) { return _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵvid"](0, [(_l()(), _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵeld"](0, 0, null, null, 15, "div", [], [[8, "className", 0]], null, null, null, null)), (_l()(), _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵeld"](1, 0, null, null, 1, "h2", [["class", "taskHeader"]], null, [[null, "click"]], function (_v, en, $event) { var ad = true; var _co = _v.component; if (("click" === en)) {
        var pd_0 = (_co.theMap.clickedFlyTo([_v.context.$implicit.long, _v.context.$implicit.lat]) !== false);
        ad = (pd_0 && ad);
    } return ad; }, null, null)), (_l()(), _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵted"](2, null, [" Task: ", " "])), (_l()(), _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵeld"](3, 0, null, null, 1, "span", [], [[8, "className", 0]], null, null, null, null)), (_l()(), _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵted"](4, null, ["(", "\u00A0Severity)"])), (_l()(), _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵeld"](5, 0, null, null, 2, "p", [["class", "createdBy"]], null, null, null, null, null)), (_l()(), _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵted"](6, null, ["Created by: ", " on ", ""])), _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵppd"](7, 1), (_l()(), _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵeld"](8, 0, null, null, 1, "p", [["class", "worker"]], null, null, null, null, null)), (_l()(), _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵted"](9, null, ["Working on it: ", " - ", ""])), (_l()(), _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵeld"](10, 0, null, null, 5, "div", [["class", "stateDue"]], null, null, null, null, null)), (_l()(), _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵeld"](11, 0, null, null, 1, "span", [], [[8, "className", 0]], null, null, null, null)), (_l()(), _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵted"](12, null, ["State: ", ""])), (_l()(), _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵeld"](13, 0, null, null, 2, "span", [["class", "dueDate"]], null, null, null, null, null)), (_l()(), _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵted"](14, null, ["Due: ", ""])), _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵppd"](15, 1)], null, function (_ck, _v) { var currVal_0 = _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵinlineInterpolate"](1, "punch ", _v.context.$implicit.selected, ""); _ck(_v, 0, 0, currVal_0); var currVal_1 = _v.context.$implicit.task; _ck(_v, 2, 0, currVal_1); var currVal_2 = _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵinlineInterpolate"](1, "severity ", _v.context.$implicit.severity.toLowerCase(), ""); _ck(_v, 3, 0, currVal_2); var currVal_3 = _v.context.$implicit.severity; _ck(_v, 4, 0, currVal_3); var currVal_4 = _v.context.$implicit.creator; var currVal_5 = _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵunv"](_v, 6, 1, _ck(_v, 7, 0, _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵnov"](_v.parent.parent, 0), _v.context.$implicit.createdOn)); _ck(_v, 6, 0, currVal_4, currVal_5); var currVal_6 = _v.context.$implicit.worker; var currVal_7 = _v.context.$implicit.trade; _ck(_v, 9, 0, currVal_6, currVal_7); var currVal_8 = _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵinlineInterpolate"](1, "taskState ", _v.context.$implicit.taskState.toLowerCase(), ""); _ck(_v, 11, 0, currVal_8); var currVal_9 = _v.context.$implicit.taskState; _ck(_v, 12, 0, currVal_9); var currVal_10 = _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵunv"](_v, 14, 0, _ck(_v, 15, 0, _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵnov"](_v.parent.parent, 0), _v.context.$implicit.due)); _ck(_v, 14, 0, currVal_10); }); }
function View_PunchComponent_1(_l) { return _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵvid"](0, [(_l()(), _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵeld"](0, 0, null, null, 6, "div", [["class", "flex-punch"]], null, null, null, null, null)), (_l()(), _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵeld"](1, 0, null, null, 1, "button", [], null, [[null, "click"]], function (_v, en, $event) { var ad = true; var _co = _v.component; if (("click" === en)) {
        var pd_0 = (_co.prevPunch() !== false);
        ad = (pd_0 && ad);
    } return ad; }, null, null)), (_l()(), _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵted"](-1, null, ["\u21FD"])), (_l()(), _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵand"](16777216, null, null, 1, null, View_PunchComponent_2)), _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵdid"](4, 278528, null, 0, _angular_common__WEBPACK_IMPORTED_MODULE_2__["NgForOf"], [_angular_core__WEBPACK_IMPORTED_MODULE_1__["ViewContainerRef"], _angular_core__WEBPACK_IMPORTED_MODULE_1__["TemplateRef"], _angular_core__WEBPACK_IMPORTED_MODULE_1__["IterableDiffers"]], { ngForOf: [0, "ngForOf"] }, null), (_l()(), _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵeld"](5, 0, null, null, 1, "button", [], null, [[null, "click"]], function (_v, en, $event) { var ad = true; var _co = _v.component; if (("click" === en)) {
        var pd_0 = (_co.nextPunch() !== false);
        ad = (pd_0 && ad);
    } return ad; }, null, null)), (_l()(), _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵted"](-1, null, ["\u21FE"]))], function (_ck, _v) { var _co = _v.component; var currVal_0 = _co.punchList; _ck(_v, 4, 0, currVal_0); }, null); }
function View_PunchComponent_3(_l) { return _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵvid"](0, [(_l()(), _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵeld"](0, 0, null, null, 2, "div", [["class", "no-trade"]], null, null, null, null, null)), (_l()(), _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵeld"](1, 0, null, null, 1, "span", [], null, null, null, null, null)), (_l()(), _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵted"](-1, null, ["No tasks for that trade found."]))], null, null); }
function View_PunchComponent_0(_l) { return _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵvid"](0, [_angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵpid"](0, _angular_common__WEBPACK_IMPORTED_MODULE_2__["DatePipe"], [_angular_core__WEBPACK_IMPORTED_MODULE_1__["LOCALE_ID"]]), _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵqud"](402653184, 1, { theMap: 0 }), (_l()(), _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵeld"](2, 0, null, null, 2, "map-box", [], null, null, null, _map_map_component_ngfactory__WEBPACK_IMPORTED_MODULE_3__["View_MapComponent_0"], _map_map_component_ngfactory__WEBPACK_IMPORTED_MODULE_3__["RenderType_MapComponent"])), _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵprd"](512, null, _services_mapbox_service__WEBPACK_IMPORTED_MODULE_4__["MapboxService"], _services_mapbox_service__WEBPACK_IMPORTED_MODULE_4__["MapboxService"], []), _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵdid"](4, 114688, [[1, 4], ["map", 4]], 0, _map_map_component__WEBPACK_IMPORTED_MODULE_5__["MapComponent"], [_services_mapbox_service__WEBPACK_IMPORTED_MODULE_4__["MapboxService"], _services_punch_service__WEBPACK_IMPORTED_MODULE_6__["PunchService"]], null, null), (_l()(), _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵand"](16777216, null, null, 1, null, View_PunchComponent_1)), _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵdid"](6, 16384, null, 0, _angular_common__WEBPACK_IMPORTED_MODULE_2__["NgIf"], [_angular_core__WEBPACK_IMPORTED_MODULE_1__["ViewContainerRef"], _angular_core__WEBPACK_IMPORTED_MODULE_1__["TemplateRef"]], { ngIf: [0, "ngIf"] }, null), (_l()(), _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵand"](16777216, null, null, 1, null, View_PunchComponent_3)), _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵdid"](8, 16384, null, 0, _angular_common__WEBPACK_IMPORTED_MODULE_2__["NgIf"], [_angular_core__WEBPACK_IMPORTED_MODULE_1__["ViewContainerRef"], _angular_core__WEBPACK_IMPORTED_MODULE_1__["TemplateRef"]], { ngIf: [0, "ngIf"] }, null)], function (_ck, _v) { var _co = _v.component; _ck(_v, 4, 0); var currVal_0 = !_co.noTrade; _ck(_v, 6, 0, currVal_0); var currVal_1 = _co.noTrade; _ck(_v, 8, 0, currVal_1); }, null); }
function View_PunchComponent_Host_0(_l) { return _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵvid"](0, [(_l()(), _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵeld"](0, 0, null, null, 2, "punch-list", [], null, null, null, View_PunchComponent_0, RenderType_PunchComponent)), _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵprd"](512, null, _services_punch_service__WEBPACK_IMPORTED_MODULE_6__["PunchService"], _services_punch_service__WEBPACK_IMPORTED_MODULE_6__["PunchService"], []), _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵdid"](2, 114688, null, 0, _punch_component__WEBPACK_IMPORTED_MODULE_7__["PunchComponent"], [_services_punch_service__WEBPACK_IMPORTED_MODULE_6__["PunchService"], _angular_router__WEBPACK_IMPORTED_MODULE_8__["ActivatedRoute"]], null, null)], function (_ck, _v) { _ck(_v, 2, 0); }, null); }
var PunchComponentNgFactory = _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵccf"]("punch-list", _punch_component__WEBPACK_IMPORTED_MODULE_7__["PunchComponent"], View_PunchComponent_Host_0, {}, {}, []);



/***/ }),

/***/ "./src/app/components/punch/punch.component.ts":
/*!*****************************************************!*\
  !*** ./src/app/components/punch/punch.component.ts ***!
  \*****************************************************/
/*! exports provided: PunchComponent */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "PunchComponent", function() { return PunchComponent; });
/* harmony import */ var _angular_core__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! @angular/core */ "./node_modules/@angular/core/fesm5/core.js");
/* harmony import */ var _angular_router__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! @angular/router */ "./node_modules/@angular/router/fesm5/router.js");
/* harmony import */ var _services_punch_service__WEBPACK_IMPORTED_MODULE_2__ = __webpack_require__(/*! ../../services/punch.service */ "./src/app/services/punch.service.ts");
/* harmony import */ var _map_map_component__WEBPACK_IMPORTED_MODULE_3__ = __webpack_require__(/*! ../map/map.component */ "./src/app/components/map/map.component.ts");




var PunchComponent = /** @class */ (function () {
    function PunchComponent(_punchServ, _route) {
        this._punchServ = _punchServ;
        this._route = _route;
        this.noTrade = false;
    }
    PunchComponent.prototype.ngOnInit = function () {
        var _this = this;
        this._route.paramMap.subscribe(function (params) {
            var trade = params.get('trade');
            if (trade) {
                console.log('if task: ', trade);
                var filteredPunches = _this._punchServ.getPunches()
                    .filter(function (punch) { return punch.trade.toLowerCase() === trade; });
                // Make sure the given trade exists
                if (filteredPunches.length > 0) {
                    filteredPunches[0].selected = 'selected';
                    _this._punchServ.punchList = filteredPunches;
                }
                else {
                    _this.noTrade = true;
                }
            }
            else {
                _this.punchList = _this._punchServ.getPunches();
            }
        });
        this.punchList = this._punchServ.punchList;
    };
    PunchComponent.prototype.prevPunch = function () {
        var currentPunchIndex = this.punchList.findIndex(function (sel) { return sel.selected === 'selected'; });
        if (currentPunchIndex >= 1) {
            this.punchList[currentPunchIndex].selected = '';
            this.punchList[currentPunchIndex - 1].selected = 'selected';
        }
        else {
            this.punchList[currentPunchIndex].selected = '';
            this.punchList[this.punchList.length - 1].selected = 'selected';
        }
    };
    PunchComponent.prototype.nextPunch = function () {
        var currentPunchIndex = this.punchList.findIndex(function (sel) { return sel.selected === 'selected'; });
        if (currentPunchIndex < this.punchList.length - 1) {
            this.punchList[currentPunchIndex].selected = '';
            this.punchList[currentPunchIndex + 1].selected = 'selected';
        }
        else {
            this.punchList[currentPunchIndex].selected = '';
            this.punchList[0].selected = 'selected';
        }
    };
    PunchComponent.prototype.removeSpaces = function (spaceyStr) {
        spaceyStr = spaceyStr.replace(/\s+/g, '');
    };
    return PunchComponent;
}());



/***/ }),

/***/ "./src/app/components/punch/punch.module.ts":
/*!**************************************************!*\
  !*** ./src/app/components/punch/punch.module.ts ***!
  \**************************************************/
/*! exports provided: PunchModule */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "PunchModule", function() { return PunchModule; });
var PunchModule = /** @class */ (function () {
    function PunchModule() {
    }
    return PunchModule;
}());



/***/ }),

/***/ "./src/app/models/geojson.ts":
/*!***********************************!*\
  !*** ./src/app/models/geojson.ts ***!
  \***********************************/
/*! exports provided: GeoJson, FeatureCollection */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "GeoJson", function() { return GeoJson; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "FeatureCollection", function() { return FeatureCollection; });
var GeoJson = /** @class */ (function () {
    function GeoJson(coordinates, properties) {
        this.properties = properties;
        this.type = 'Feature';
        this.geometry = {
            type: 'Point',
            coordinates: coordinates
        };
    }
    return GeoJson;
}());

var FeatureCollection = /** @class */ (function () {
    function FeatureCollection(features) {
        this.features = features;
        this.type = 'FeatureCollection';
    }
    ;
    return FeatureCollection;
}());



/***/ }),

/***/ "./src/app/models/punch.ts":
/*!*********************************!*\
  !*** ./src/app/models/punch.ts ***!
  \*********************************/
/*! exports provided: Punch */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "Punch", function() { return Punch; });
var Punch = /** @class */ (function () {
    function Punch() {
    }
    return Punch;
}());



/***/ }),

/***/ "./src/app/models/punchMarkers.ts":
/*!****************************************!*\
  !*** ./src/app/models/punchMarkers.ts ***!
  \****************************************/
/*! exports provided: PunchMarkers */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "PunchMarkers", function() { return PunchMarkers; });
var PunchMarkers = [
    {
        id: 0,
        task: 'Lightbulbs',
        worker: 'Bob',
        creator: 'Larry',
        createdOn: new Date('05/06/2019 04:00:00 CST'),
        due: new Date('05/10/2019 04:00:00 CST'),
        completed: false,
        taskState: 'In Progress',
        trade: 'Electrician',
        severity: 'High',
        long: '-96.9320211692925',
        lat: '32.64428173841969'
    },
    {
        id: 1,
        task: 'South Wall',
        worker: 'Harold',
        creator: 'Larry',
        createdOn: new Date('04/08/2019 04:00:00 CST'),
        due: new Date('05/10/2019 04:00:00 CST'),
        completed: false,
        taskState: 'In Progress',
        trade: 'Masonry',
        severity: 'Medium',
        long: '-96.92662456475334',
        lat: '32.64348673729481'
    },
    {
        id: 2,
        task: 'Back Porch',
        worker: 'Sarah',
        creator: 'Larry',
        createdOn: new Date('04/18/2019 04:00:00 CST'),
        due: new Date('05/12/2019 04:00:00 CST'),
        completed: false,
        taskState: 'Blocked',
        trade: 'Concrete',
        severity: 'Medium',
        long: '-96.93589427911297',
        lat: '32.646296311889884',
        selected: 'selected'
    },
    {
        id: 3,
        task: 'Laundry Line',
        worker: 'Patrick',
        creator: 'Harry',
        createdOn: new Date('05/18/2019 04:00:00 CST'),
        due: new Date('05/12/2019 04:00:00 CST'),
        completed: false,
        taskState: 'Blocked',
        trade: 'Plumbing',
        severity: 'Low',
        long: '-96.93777182542118',
        lat: '32.64614273614187'
    },
    {
        id: 4,
        task: 'Fence',
        worker: 'Juan',
        creator: 'Carrey',
        createdOn: new Date('02/28/2019 04:00:00 CST'),
        due: new Date('03/12/2019 04:00:00 CST'),
        completed: true,
        taskState: 'Complete',
        trade: 'Fencing',
        severity: 'Low',
        long: '-96.9369564338815',
        lat: '32.64419139774364'
    },
    {
        id: 5,
        task: 'Unit Installation',
        worker: 'Roger',
        creator: 'Harry',
        createdOn: new Date('05/07/2019 04:00:00 CST'),
        due: new Date('05/12/2019 04:00:00 CST'),
        completed: false,
        taskState: 'In Progress',
        trade: 'HVAC',
        severity: 'High',
        long: '-96.92879178964147',
        lat: '32.64435401090057'
    },
    {
        id: 6,
        task: 'Pantry Floors',
        worker: 'Jose',
        creator: 'Larry',
        createdOn: new Date('05/01/2019 04:00:00 CST'),
        due: new Date('05/12/2019 04:00:00 CST'),
        completed: false,
        taskState: 'In Progress',
        trade: 'Flooring',
        severity: 'Medium',
        long: '-96.92643144570759',
        lat: '32.646332447328376'
    },
    {
        id: 7,
        task: 'Wall of the North',
        worker: 'Edd',
        creator: 'Larry',
        createdOn: new Date('04/08/2019 04:00:00 CST'),
        due: new Date('05/26/2019 04:00:00 CST'),
        completed: false,
        taskState: 'In Progress',
        trade: 'Masonry',
        severity: 'Medium',
        long: '-96.93211359154917',
        lat: '32.64742572181363'
    },
];


/***/ }),

/***/ "./src/app/services/mapbox.service.ts":
/*!********************************************!*\
  !*** ./src/app/services/mapbox.service.ts ***!
  \********************************************/
/*! exports provided: MapboxService */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "MapboxService", function() { return MapboxService; });
/* harmony import */ var _environments_environment__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! ../../environments/environment */ "./src/environments/environment.ts");
/* harmony import */ var mapbox_gl__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! mapbox-gl */ "./node_modules/mapbox-gl/dist/mapbox-gl.js");
/* harmony import */ var mapbox_gl__WEBPACK_IMPORTED_MODULE_1___default = /*#__PURE__*/__webpack_require__.n(mapbox_gl__WEBPACK_IMPORTED_MODULE_1__);


var MapboxService = /** @class */ (function () {
    function MapboxService() {
        mapbox_gl__WEBPACK_IMPORTED_MODULE_1__["accessToken"] = _environments_environment__WEBPACK_IMPORTED_MODULE_0__["environment"].mapbox.accessToken;
    }
    return MapboxService;
}());



/***/ }),

/***/ "./src/app/services/punch.service.ts":
/*!*******************************************!*\
  !*** ./src/app/services/punch.service.ts ***!
  \*******************************************/
/*! exports provided: PunchService */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "PunchService", function() { return PunchService; });
/* harmony import */ var _models_punchMarkers__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! ../models/punchMarkers */ "./src/app/models/punchMarkers.ts");

var PunchService = /** @class */ (function () {
    function PunchService() {
        this.getPunches();
    }
    PunchService.prototype.getPunches = function () {
        return this.punchList = _models_punchMarkers__WEBPACK_IMPORTED_MODULE_0__["PunchMarkers"];
    };
    PunchService.prototype.getSelectedPunch = function () {
        return this.punchList.find(function (punch) { return punch.selected === 'selected'; });
    };
    PunchService.prototype.getSelectedPunchIndex = function () {
        return this.punchList.findIndex(function (punch) { return punch.selected === 'selected'; });
    };
    PunchService.prototype.getSelectedId = function () {
        var selected = this.punchList.filter(function (punch) { return punch.selected === 'selected'; });
        return selected[0].id;
    };
    return PunchService;
}());



/***/ }),

/***/ "./src/environments/environment.ts":
/*!*****************************************!*\
  !*** ./src/environments/environment.ts ***!
  \*****************************************/
/*! exports provided: environment */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "environment", function() { return environment; });
// This file can be replaced during build by using the `fileReplacements` array.
// `ng build --prod` replaces `environment.ts` with `environment.prod.ts`.
// The list of file replacements can be found in `angular.json`.
var environment = {
    production: false,
    mapbox: {
        accessToken: 'pk.eyJ1IjoiZXJxd29yayIsImEiOiJjanZlamthZWkwMjBpNDR0aHA2YTFndmx3In0.qif3nFurqiDrZD-BergJfw'
    }
};
/*
 * For easier debugging in development mode, you can import the following file
 * to ignore zone related error stack frames such as `zone.run`, `zoneDelegate.invokeTask`.
 *
 * This import should be commented out in production mode because it will have a negative impact
 * on performance if an error is thrown.
 */
// import 'zone.js/dist/zone-error';  // Included with Angular CLI.


/***/ }),

/***/ "./src/main.ts":
/*!*********************!*\
  !*** ./src/main.ts ***!
  \*********************/
/*! no exports provided */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var _angular_core__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! @angular/core */ "./node_modules/@angular/core/fesm5/core.js");
/* harmony import */ var _environments_environment__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! ./environments/environment */ "./src/environments/environment.ts");
/* harmony import */ var _app_app_module_ngfactory__WEBPACK_IMPORTED_MODULE_2__ = __webpack_require__(/*! ./app/app.module.ngfactory */ "./src/app/app.module.ngfactory.js");
/* harmony import */ var _angular_platform_browser__WEBPACK_IMPORTED_MODULE_3__ = __webpack_require__(/*! @angular/platform-browser */ "./node_modules/@angular/platform-browser/fesm5/platform-browser.js");




if (_environments_environment__WEBPACK_IMPORTED_MODULE_1__["environment"].production) {
    Object(_angular_core__WEBPACK_IMPORTED_MODULE_0__["enableProdMode"])();
}
_angular_platform_browser__WEBPACK_IMPORTED_MODULE_3__["platformBrowser"]().bootstrapModuleFactory(_app_app_module_ngfactory__WEBPACK_IMPORTED_MODULE_2__["AppModuleNgFactory"])
    .catch(function (err) { return console.error(err); });


/***/ }),

/***/ 0:
/*!***************************!*\
  !*** multi ./src/main.ts ***!
  \***************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

module.exports = __webpack_require__(/*! D:\Web\PunchList\src\main.ts */"./src/main.ts");


/***/ })

},[[0,"runtime","vendor"]]]);
//# sourceMappingURL=main.js.map